### ISSUE TITLE
like 10 nodes missing....

### ISSUE THREAD

**Issue by lgleim** [pi0/gluu-docker#3]
WTF... in your proxy configuration you use the hosts passport, asimba, oxauth-rp, idp and cas, none of which are actually availabe with the provided compose script. This is in no way runnable. You should update the README accordingly. I just wasted a day and a half on this...

**Comment by pi0** [comment]
@lgleim This is just default configuration forked from gluu-community-edition, only standard components (identity, oxauth, ldap) are currently supported as is documented in [docker-compose](https://github.com/pi0/gluu-docker/blob/master/docker-compose.yml) file.
Asking community is always better idea :)

**Comment by lgleim** [comment]
Allright. Sorry for the rough tone. I will create a pull request with some readme updates. I just set everything up and have it working in less then 3 minutes now that you provided (especially the ssl setup) clarifications.
